// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"time"
)

type Quiz struct {
	ID      int64
	Name    string
	Data    []byte
	Created time.Time
	Updated time.Time
}

type QuizSession struct {
	ID                int64
	StudentID         int64
	QuizID            int64
	QuestionsAnswered int64
	Active            bool
	Created           time.Time
	Updated           time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID         int64
	Username   string
	ClassCode  string
	Statistics interface{}
	Created    time.Time
	Updated    time.Time
}
