// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"time"
)

type Quiz struct {
	ID      int
	Name    string
	Data    []byte
	Created time.Time
	Updated time.Time
}

type QuizSession struct {
	ID                int
	StudentID         int
	QuizID            int
	QuestionsAnswered int
	Active            bool
	Created           time.Time
	Updated           time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID        int
	Username  string
	ClassCode string
	Created   time.Time
	Updated   time.Time
}

type TagAttempt struct {
	ID        int
	StudentID int
	Tag       string
	Correct   bool
	Created   time.Time
	Updated   time.Time
}
