// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"encoding/json"
	"time"
)

type Quiz struct {
	ID      int64
	Name    string
	Data    json.RawMessage
	Created time.Time
	Updated time.Time
}

type QuizSession struct {
	ID        int64
	StudentID int64
	QuizID    int64
	Data      interface{}
	Created   time.Time
	Updated   time.Time
}

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type Student struct {
	ID           int64
	Email        string
	Username     string
	PasswordHash string
	Statistics   interface{}
	Created      time.Time
	Updated      time.Time
}
