package arabic

var States = []string{
	FromBuckwalter("mbtd>"),
	FromBuckwalter("xbr"),
	FromBuckwalter("fAEl nA}b"),
	FromBuckwalter("fAEl"),
	FromBuckwalter("Asm kAn w>xwAthA"),
	FromBuckwalter("Asm <n w>xwAthA"),
	FromBuckwalter("mfEwl bh"),
	FromBuckwalter("mfEwl bh vAn"),
	FromBuckwalter("mfEwl bh vAlv"),
	FromBuckwalter("mfEwl fyh"),
	FromBuckwalter("mfEwl mTlq"),
	FromBuckwalter("mfEwl l>jlh"),
	FromBuckwalter("mfEwl mEh"),
	FromBuckwalter("HAl"),
	FromBuckwalter("tmyyz"),
	FromBuckwalter("mstvnY"),
	FromBuckwalter("HSr"),
	FromBuckwalter("mnAdY"),
	FromBuckwalter("Asm wxbr Zn w>xwAthA"),
	FromBuckwalter("Asm wxbr Hrf nfy"),
	FromBuckwalter("Asm <n w>xwAthA"),
	FromBuckwalter("xbr kAn w>xwAthA"),
	FromBuckwalter("Asm bEd Hrf jr"),
	FromBuckwalter("mDAf <lyh"),
	FromBuckwalter("mDArE mrfwE"),
	FromBuckwalter("mDArE mnSwb bHrf AlnSb"),
	FromBuckwalter("mDArE mjzwm bHrf Aljzm"),
	FromBuckwalter("mDArE mjzwm b>dAp Al$rT AljAzm"),
	FromBuckwalter("nEt"),
	FromBuckwalter("Asm mETwf"),
	FromBuckwalter("twkyd"),
	FromBuckwalter("bdl"),
}
